version: "3.7"
services:
  backend:
    ports:
      - "8080:80"
    image: "docker.pkg.github.com/lusinx/pressx/backend:dev-env"
    container_name: "backend"
    command: modd
    volumes:
      - ./backend:/pressx
  admin:
    ports:
      - "8000:8000"
      - "8888:8888"
    image: "pressx-dev-admin"
    container_name: "pressx-dev-admin"
    build:
      context: "admin"
      dockerfile: "development.Dockerfile"
    working_dir: "/admin"
    command: sh -c "npm i && npm start"
    volumes:
      - ./admin:/admin
