version: "3.7"
services:
  backend:
    ports:
      - "8080:80"
    image: "docker.pkg.github.com/lusinx/pressx/backend:dev-env"
    container_name: "backend"
    command: modd
    volumes:
      - ./backend:/pressx
    environment:
      - POSTGRES_HOST=172.16.238.13
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=${POSTGRES_USER}
    networks:
      backend:
        ipv4_address: 172.16.238.10

  postgres:
    image: "postgres:12-alpine"
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    networks:
      backend:
        ipv4_address: 172.16.238.13

  adminer:
    image: adminer
    restart: always
    networks:
      backend:
        ipv4_address: 172.16.238.12
    ports:
      - 9999:8080

  admin:
    ports:
      - "8000:8000"
      - "8888:8888"
    image: "pressx-dev-admin"
    container_name: "pressx-dev-admin"
    build:
      context: "admin"
      dockerfile: "development.Dockerfile"
    working_dir: "/admin"
    command: sh -c "npm i && npm start"
    volumes:
      - ./admin:/admin

networks:
  # Backend bridged network
  backend:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
